import type { AssessmentQuestion, Exercise } from './types';

export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: 1,
    scenario: "Your friend trips and drops their lunch tray in the cafeteria. Everyone is looking. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "🤝", label: "Help them pick everything up and say it's okay", scores: { empathy: 3, socialSkills: 2 } },
      { emoji: "😶", label: "Look away and pretend you didn't see", scores: { empathy: 0, socialSkills: 0 } },
      { emoji: "🗣️", label: "Tell everyone to stop staring", scores: { empathy: 2, socialSkills: 3, motivation: 1 } },
      { emoji: "😊", label: "Share your lunch with them", scores: { empathy: 3, socialSkills: 2, motivation: 2 } },
    ],
  },
  {
    id: 2,
    scenario: "You're working on a group project and one person isn't doing their part. How do you feel and respond?",
    ageGroup: '8-10',
    options: [
      { emoji: "😤", label: "Get angry and tell the teacher", scores: { selfRegulation: 0, socialSkills: 1 } },
      { emoji: "💬", label: "Calmly ask them if they need help with their part", scores: { empathy: 2, selfRegulation: 3, socialSkills: 3 } },
      { emoji: "😔", label: "Just do their part yourself without saying anything", scores: { selfRegulation: 1, selfAwareness: 1 } },
      { emoji: "🤔", label: "Try to understand why they might be struggling", scores: { empathy: 3, selfAwareness: 2, selfRegulation: 2 } },
    ],
  },
  {
    id: 3,
    scenario: "You notice a new kid sitting alone at recess. They look nervous. What happens next?",
    ageGroup: '8-10',
    options: [
      { emoji: "👋", label: "Walk over and invite them to play with you", scores: { empathy: 3, socialSkills: 3, motivation: 2 } },
      { emoji: "📖", label: "You're busy with your own friends, but you smile at them", scores: { empathy: 1, socialSkills: 1 } },
      { emoji: "🎮", label: "Ask your friend group if they can join", scores: { empathy: 2, socialSkills: 3, motivation: 1 } },
      { emoji: "💭", label: "Remember how you felt being new and go talk to them", scores: { empathy: 3, selfAwareness: 3, motivation: 2 } },
    ],
  },
  {
    id: 4,
    scenario: "You studied really hard for a test but got a lower grade than expected. How do you handle it?",
    ageGroup: '8-10',
    options: [
      { emoji: "😢", label: "Cry and feel like giving up", scores: { selfAwareness: 1, selfRegulation: 0 } },
      { emoji: "🔍", label: "Look at what you got wrong and make a study plan", scores: { selfRegulation: 3, selfAwareness: 2, motivation: 3 } },
      { emoji: "😡", label: "Think the test was unfair and complain", scores: { selfRegulation: 0, selfAwareness: 0 } },
      { emoji: "💪", label: "Feel disappointed but tell yourself you'll do better next time", scores: { selfRegulation: 2, selfAwareness: 2, motivation: 2 } },
    ],
  },
  {
    id: 5,
    scenario: "Your sibling broke your favorite toy accidentally. They look really sorry. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "😤", label: "Yell at them and say they owe you a new one", scores: { selfRegulation: 0, empathy: 0 } },
      { emoji: "🫂", label: "Take a deep breath, then tell them it's okay and accidents happen", scores: { selfRegulation: 3, empathy: 3, selfAwareness: 2 } },
      { emoji: "🚶", label: "Walk away to cool down before talking about it", scores: { selfRegulation: 3, selfAwareness: 3 } },
      { emoji: "😢", label: "Cry but don't blame them", scores: { selfAwareness: 2, selfRegulation: 1, empathy: 1 } },
    ],
  },
  {
    id: 6,
    scenario: "Two of your friends are in an argument and both want you to pick a side. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "⚖️", label: "Listen to both sides and help them find a compromise", scores: { socialSkills: 3, empathy: 3, selfRegulation: 2 } },
      { emoji: "🏃", label: "Avoid both of them until it blows over", scores: { selfRegulation: 1, socialSkills: 0 } },
      { emoji: "👂", label: "Tell each one separately that you understand how they feel", scores: { empathy: 3, socialSkills: 2, selfAwareness: 1 } },
      { emoji: "🤷", label: "Pick the friend you agree with more", scores: { selfAwareness: 1, socialSkills: 0 } },
    ],
  },
  {
    id: 7,
    scenario: "You see someone being teased by a group of kids. The person being teased looks upset. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "🦸", label: "Stand up and tell the group to stop", scores: { empathy: 3, motivation: 3, socialSkills: 2 } },
      { emoji: "🤝", label: "Go sit with the person being teased and talk to them", scores: { empathy: 3, socialSkills: 3, motivation: 2 } },
      { emoji: "👩‍🏫", label: "Tell a teacher or adult right away", scores: { socialSkills: 2, motivation: 2, selfRegulation: 2 } },
      { emoji: "😶", label: "Feel bad but do nothing because you're scared", scores: { selfAwareness: 2, empathy: 1, selfRegulation: 0 } },
    ],
  },
  {
    id: 8,
    scenario: "You promised to help a friend but then got invited to a really fun event at the same time. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "🤝", label: "Keep your promise to your friend", scores: { socialSkills: 3, empathy: 2, selfRegulation: 3 } },
      { emoji: "📱", label: "Call your friend, explain honestly, and ask to reschedule", scores: { socialSkills: 2, empathy: 2, selfAwareness: 2, selfRegulation: 2 } },
      { emoji: "🎉", label: "Go to the fun event and make an excuse to your friend", scores: { selfRegulation: 0, socialSkills: 0, empathy: 0 } },
      { emoji: "🤔", label: "See if your friend can come to the event too", scores: { socialSkills: 3, empathy: 2, motivation: 2 } },
    ],
  },
  {
    id: 9,
    scenario: "You're feeling really overwhelmed with homework, activities, and chores. Everything feels like too much.",
    ageGroup: '8-10',
    options: [
      { emoji: "📝", label: "Make a list, prioritize, and tackle things one at a time", scores: { selfRegulation: 3, selfAwareness: 2, motivation: 3 } },
      { emoji: "🗣️", label: "Talk to a parent or teacher about how you're feeling", scores: { selfAwareness: 3, socialSkills: 2, selfRegulation: 2 } },
      { emoji: "😫", label: "Shut down and avoid everything", scores: { selfRegulation: 0, selfAwareness: 0, motivation: 0 } },
      { emoji: "🧘", label: "Take 5 deep breaths, then start with the easiest task", scores: { selfRegulation: 3, selfAwareness: 3, motivation: 2 } },
    ],
  },
  {
    id: 10,
    scenario: "Your friend shares a secret with you. Later, another friend asks you about it. What do you do?",
    ageGroup: '8-10',
    options: [
      { emoji: "🤐", label: "Keep the secret and say you don't know anything", scores: { socialSkills: 3, empathy: 2, selfRegulation: 3 } },
      { emoji: "🗣️", label: "Tell them since it's not a big deal", scores: { socialSkills: 0, empathy: 0, selfRegulation: 0 } },
      { emoji: "💬", label: "Say 'That's not my story to tell' without being rude", scores: { socialSkills: 3, empathy: 3, selfRegulation: 3, selfAwareness: 2 } },
      { emoji: "🤔", label: "Tell part of it but leave out the important details", scores: { socialSkills: 1, selfRegulation: 1 } },
    ],
  },
];

export const exercises: Exercise[] = [
  {
    id: 'empathy-mirror',
    title: 'The Empathy Mirror',
    description: 'Practice seeing the world through someone else\'s eyes by exploring different perspectives on everyday situations.',
    category: 'empathy',
    ageGroups: ['8-10', '11-13'],
    duration: '10 min',
    difficulty: 'beginner',
    icon: '🪞',
    scenario: 'Your classmate Maya seems quiet today. She usually talks a lot and laughs with everyone. At lunch, she sits alone and barely touches her food.\n\nImagine you are Maya. Think about:\n- What might have happened to make you feel this way?\n- What would you want your friends to do?\n- How would it feel if someone noticed and asked if you were okay?',
    reflectionPrompts: [
      'What feelings did you imagine Maya might be having?',
      'Was it easy or hard to imagine being in her shoes?',
      'What would be the kindest thing a friend could do in this situation?',
      'Has there been a time when you wished someone noticed how you were feeling?',
    ],
  },
  {
    id: 'emotion-volcano',
    title: 'The Emotion Volcano',
    description: 'Learn to recognize when big feelings are building up and discover healthy ways to release them before they erupt.',
    category: 'self-regulation',
    ageGroups: ['5-7', '8-10'],
    duration: '8 min',
    difficulty: 'beginner',
    icon: '🌋',
    scenario: 'Imagine your emotions are like a volcano. Sometimes feelings build up inside:\n\n🟢 Green Zone: Calm, happy, relaxed\n🟡 Yellow Zone: Frustrated, worried, annoyed\n🔴 Red Zone: Furious, terrified, overwhelmed\n\nThink about your day today:\n- What zone are you in right now?\n- What happened today that moved you between zones?\n- What helps you get back to green when you\'re in yellow or red?',
    reflectionPrompts: [
      'What zone are you in right now?',
      'What are your personal warning signs that you\'re moving from green to yellow?',
      'Name 3 things that help you cool down when emotions feel big.',
      'Is it okay to feel big emotions? Why or why not?',
    ],
  },
  {
    id: 'peace-bridge',
    title: 'The Peace Bridge',
    description: 'Walk through a step-by-step conflict resolution process using real scenarios kids face every day.',
    category: 'conflict-resolution',
    ageGroups: ['8-10', '11-13', '14-15'],
    duration: '12 min',
    difficulty: 'intermediate',
    icon: '🌉',
    scenario: 'You and your best friend both want to be the team captain for the class project. You both feel strongly about it and the conversation is getting heated.\n\nThe Peace Bridge has 5 steps:\n1. STOP - Take 3 deep breaths\n2. SAY - "I feel ___ because ___"\n3. LISTEN - Hear the other person\'s feelings without interrupting\n4. THINK - Brainstorm solutions together\n5. CHOOSE - Pick a solution that works for both people\n\nWalk through each step for this situation.',
    reflectionPrompts: [
      'Which step of the Peace Bridge is hardest for you?',
      'What solution did you come up with?',
      'How does it feel when someone really listens to your side?',
      'Can you think of a real conflict where you could use these steps?',
    ],
  },
  {
    id: 'friendship-architect',
    title: 'Friendship Architect',
    description: 'Build stronger friendships by understanding what makes relationships work and practicing key social skills.',
    category: 'social-skills',
    ageGroups: ['8-10', '11-13'],
    duration: '10 min',
    difficulty: 'beginner',
    icon: '🏗️',
    scenario: 'Imagine friendships are like buildings. They need a strong foundation and careful construction:\n\n🧱 Foundation: Trust and honesty\n🪟 Windows: Being open about feelings\n🚪 Door: Welcoming new friends\n🏠 Roof: Protecting each other\n\nThink about your closest friendship:\n- Which parts of the building are strongest?\n- Which parts might need repair?\n- What\'s one thing you could do this week to strengthen your friendship building?',
    reflectionPrompts: [
      'What quality do you value most in a friend?',
      'What quality do you bring to your friendships?',
      'Is there a friendship that needs some repair work?',
      'How can you be a better friend this week?',
    ],
  },
  {
    id: 'feelings-detective',
    title: 'Feelings Detective',
    description: 'Sharpen your ability to read emotions in others through facial expressions, body language, and tone of voice.',
    category: 'empathy',
    ageGroups: ['5-7', '8-10'],
    duration: '8 min',
    difficulty: 'beginner',
    icon: '🔍',
    scenario: 'You are a Feelings Detective! Your mission is to discover how people around you are really feeling.\n\nClue Checklist:\n👀 Eyes: Are they bright, teary, looking away?\n👄 Mouth: Smiling, frowning, tight-lipped?\n🤲 Hands: Relaxed, clenched, fidgeting?\n🧍 Body: Standing tall, slouching, turned away?\n🗣️ Voice: Loud, quiet, shaky, fast?\n\nThink about someone you saw today. What clues did their body give you about how they were feeling?',
    reflectionPrompts: [
      'What emotion clues are easiest for you to spot?',
      'Which clues are hardest to read?',
      'Have you ever misread someone\'s emotions? What happened?',
      'How does paying attention to these clues help you be a better friend?',
    ],
  },
  {
    id: 'calm-toolkit',
    title: 'My Calm Toolkit',
    description: 'Create your personal collection of calming strategies that work specifically for you.',
    category: 'self-regulation',
    ageGroups: ['5-7', '8-10', '11-13'],
    duration: '10 min',
    difficulty: 'beginner',
    icon: '🧰',
    scenario: 'Everyone needs a toolkit for when emotions get big. Let\'s build yours!\n\nFor each category, pick your favorite calming strategy:\n\n🫁 Breathing: Box breathing (4-4-4-4), balloon breaths, or star breathing?\n🏃 Movement: Jumping jacks, stretching, walking, or dancing?\n🧠 Thinking: Counting backwards, positive self-talk, or visualization?\n🎨 Creative: Drawing, writing, music, or building something?\n🌿 Sensory: Holding ice, smelling lavender, squeezing a stress ball?\n\nNow practice your #1 strategy for 2 minutes.',
    reflectionPrompts: [
      'Which calming strategy worked best for you today?',
      'When was the last time you needed your calm toolkit?',
      'Did practicing the strategy change how your body feels?',
      'Who could you share your toolkit with?',
    ],
  },
  {
    id: 'perspective-swap',
    title: 'The Perspective Swap',
    description: 'Step into different roles in a conflict to understand how everyone involved might be feeling.',
    category: 'conflict-resolution',
    ageGroups: ['11-13', '14-15'],
    duration: '15 min',
    difficulty: 'advanced',
    icon: '🔄',
    scenario: 'Scenario: During a class presentation, someone laughed at your friend\'s project. Your friend got upset and said something mean back. Now the teacher is involved.\n\nRound 1: You are YOUR FRIEND\n- How do you feel about being laughed at?\n- Why did you say something mean back?\n- What do you need right now?\n\nRound 2: You are THE PERSON WHO LAUGHED\n- Why did you laugh? Was it intentional?\n- How do you feel now that things escalated?\n- What would you say if you could redo that moment?\n\nRound 3: You are THE TEACHER\n- What do you see happening?\n- How can you help both students?\n- What\'s a fair resolution?',
    reflectionPrompts: [
      'Which perspective was most surprising to explore?',
      'Did seeing the situation from multiple angles change your opinion?',
      'What\'s the difference between a reason and an excuse?',
      'How can understanding all perspectives help resolve conflicts?',
    ],
  },
  {
    id: 'compliment-chain',
    title: 'The Compliment Chain',
    description: 'Practice giving genuine, specific compliments that make people feel truly seen and valued.',
    category: 'social-skills',
    ageGroups: ['5-7', '8-10', '11-13'],
    duration: '8 min',
    difficulty: 'beginner',
    icon: '🔗',
    scenario: 'A great compliment is specific and genuine. Compare these:\n\n❌ "You\'re nice" (generic)\n✅ "I noticed how you helped the new kid find their classroom today. That was really kind." (specific)\n\nPractice crafting compliments for:\n1. A family member - something specific they did recently\n2. A friend - a quality you admire in them.\n3. Yourself! - something you\'re proud of.\n\nBonus: Actually deliver one of these compliments today!',
    reflectionPrompts: [
      'Which compliment was easiest to write? Hardest?',
      'How does it feel to give a genuine compliment?',
      'Why is being specific important in a compliment?',
      'How did you feel giving yourself a compliment?',
    ],
  },
];

export const categoryInfo: Record<string, { label: string; color: string; icon: string; description: string }> = {
  empathy: {
    label: 'Empathy Training',
    color: 'var(--pink)',
    icon: '💗',
    description: 'Understanding and sharing the feelings of others',
  },
  'self-regulation': {
    label: 'Self-Regulation',
    color: 'var(--teal)',
    icon: '🧘',
    description: 'Managing emotions and behaviors effectively',
  },
  'conflict-resolution': {
    label: 'Conflict Resolution',
    color: 'var(--amber)',
    icon: '🕊️',
    description: 'Resolving disagreements peacefully and fairly',
  },
  'social-skills': {
    label: 'Social Skills',
    color: 'var(--violet)',
    icon: '🤝',
    description: 'Building and maintaining healthy relationships',
  },
};

export const badges = [
  { id: 'first-assessment', name: 'Self-Explorer', description: 'Complete your first EQ assessment', icon: '🧭' },
  { id: 'first-exercise', name: 'Emotion Apprentice', description: 'Complete your first exercise', icon: '🌱' },
  { id: 'five-exercises', name: 'EQ Builder', description: 'Complete 5 exercises', icon: '🏗️' },
  { id: 'all-categories', name: 'Well-Rounded', description: 'Try exercises from all 4 categories', icon: '🌈' },
  { id: 'streak-3', name: 'Consistent Grower', description: 'Maintain a 3-day streak', icon: '🔥' },
  { id: 'streak-7', name: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '⭐' },
];
